version: '2'
services:
  nginx:
      image: nginx:1.13-alpine
      container_name: nginx
      ports:
        - 80:80
      volumes:
        - ./:/etc/nginx/conf.d/
      command: sh -c "cd /home/app/backend && ./gradlew build && java -jar build/libs/backend.jar"
      networks:
        main:
          aliases:
            - nginx
networks:
  main:
