version: '2'
services:
  nginx:
      image: nginx:1.13-alpine
      container_name: nginx
      ports:
        - 80:80
      volumes:
        - ./default.conf:/etc/nginx/conf.d/default.conf
      networks:
        main:
          aliases:
            - nginx
